Service login using private key
philips-labs/igtcloud-client pull request #20
Opened 2023-03-02 10:47 UTC by koendelaat

2023-03-02 10:53 UTC, Laugslander approved these changes

2023-03-02 12:33 UTC, pbronneberg requested changes
Please update README.md. Add instructions on how to use the client with service keys. Also add instructions on how to obtain such a key

2023-03-02 12:36 UTC, pbronneberg requested changes

2023-03-07 07:58 UTC, pbronneberg approved these changes

2023-03-07 07:58 UTC, merged